variable "location" {
  description = "Azure region for resources to be deployed to."
  type        = string
  default     = "uksouth"
}

locals {
  applications = {
    "STG-AI-Justice-Transcribe-Devl" = {
      notes                          = "Justice AI Transcribe Devl App"
      service_management_reference   = "IDAM-5036"
      logo_image                     = "./assets/MOJ_Lesser_Arms_Stacked_HEX_215x215.jpg"
      display_name                   = "STG-AI-Justice-Transcribe-Devl"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_contacts           = ["Sam.Lhuillier@justice.gov.uk", "Harry.Waterman@justice.gov.uk", "Ehsan.Ashouri@justice.gov.uk"]
      owners                         = ["Sam.Lhuillier@justice.gov.uk", "Harry.Waterman@justice.gov.uk", "Ehsan.Ashouri@justice.gov.uk"]
      allowed_groups                 = ["JusticeTranscribeTeam"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = ["https://justicetranscribe-devl-frontend.azurewebsites.net/.auth/login/aad/callback"]
      mobile_desktop_redirect_uris   = []
      access_token_issuance_enabled  = false
      id_token_issuance_enabled      = true
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read", "offline_access"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
        custom_single_sign_on         = null
      }
      identifier_uris                = null
      api = {
        known_client_applications      = []
        mapped_claims_enabled          = false
        requested_access_token_version = null
        oauth2_permission_scope        = []
      }
      tags                           = []
      custom_application_permissions = []
      spa_redirect_uris              = []
    },
    "STG-AI-Langfuse-Devl" = {
      notes                          = "Justice AI Langfuse Devl App"
      service_management_reference   = "IDAM-5036"
      logo_image                     = "./assets/MOJ_Lesser_Arms_Stacked_HEX_215x215.jpg"
      display_name                   = "STG-AI-Langfuse-Devl"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_contacts           = ["Sam.Lhuillier@justice.gov.uk", "Harry.Waterman@justice.gov.uk", "Ehsan.Ashouri@justice.gov.uk"]
      owners                         = ["Sam.Lhuillier@justice.gov.uk", "Harry.Waterman@justice.gov.uk", "Ehsan.Ashouri@justice.gov.uk"]
      allowed_groups                 = ["Justice-ai-unit-staff"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = []
      mobile_desktop_redirect_uris   = []
      access_token_issuance_enabled  = false
      id_token_issuance_enabled      = true
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
        custom_single_sign_on         = null
      }
      identifier_uris                = null
      api = {
        known_client_applications      = []
        mapped_claims_enabled          = false
        requested_access_token_version = null
        oauth2_permission_scope        = []
      }
      tags                           = []
      custom_application_permissions = []
      spa_redirect_uris              = []
    },
    "STG-AI-Prompt-Hub-Devl" = {
      notes                          = "Justice AI Prompt Hub App Devl"
      service_management_reference   = "IDAM-5036"
      logo_image                     = "./assets/MOJ_Lesser_Arms_Stacked_HEX_215x215.jpg"
      display_name                   = "STG-AI-Prompt-Hub-Devl"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_contacts           = ["Sam.Lhuillier@justice.gov.uk", "Harry.Waterman@justice.gov.uk", "Ehsan.Ashouri@justice.gov.uk"]
      owners                         = ["Sam.Lhuillier@justice.gov.uk", "Harry.Waterman@justice.gov.uk", "Ehsan.Ashouri@justice.gov.uk"]
      allowed_groups                 = ["Justice-ai-unit-staff"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = ["https://prompthub-devl-frontend.azurewebsites.net/.auth/login/aad/callback"]
      mobile_desktop_redirect_uris   = []
      access_token_issuance_enabled  = false
      id_token_issuance_enabled      = true
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
        custom_single_sign_on         = null
      }
      identifier_uris                = null
      api = {
        known_client_applications      = []
        mapped_claims_enabled          = false
        requested_access_token_version = null
        oauth2_permission_scope        = []
      }
      tags                           = []
      custom_application_permissions = []
      spa_redirect_uris              = []
    },
    "STG-AI-Redbox-Tracker-Devl" = {
      notes                          = "Justice AI Redbox Tracker App Devl"
      service_management_reference   = "IDAM-5036"
      logo_image                     = "./assets/MOJ_Lesser_Arms_Stacked_HEX_215x215.jpg"
      display_name                   = "STG-AI-Redbox-Tracker-Devl"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_contacts           = ["Sam.Lhuillier@justice.gov.uk", "Harry.Waterman@justice.gov.uk", "Ehsan.Ashouri@justice.gov.uk"]
      owners                         = ["Sam.Lhuillier@justice.gov.uk", "Harry.Waterman@justice.gov.uk", "Ehsan.Ashouri@justice.gov.uk"]
      allowed_groups                 = ["Justice-ai-unit-staff"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = ["https://redbox-tracker-devl-frontend.azurewebsites.net/.auth/login/aad/callback"]
      mobile_desktop_redirect_uris   = []
      access_token_issuance_enabled  = false
      id_token_issuance_enabled      = true
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
        custom_single_sign_on         = null
      }
      identifier_uris                = null
      api = {
        known_client_applications      = []
        mapped_claims_enabled          = false
        requested_access_token_version = null
        oauth2_permission_scope        = []
      }
      tags                           = []
      custom_application_permissions = []
      spa_redirect_uris              = []
    },
    "STG-AI-Deployed-Cookiecutter-Devl" = {
      notes                          = "Justice AI Deployed Cookiecutter App"
      service_management_reference   = "IDAM-5036"
      logo_image                     = "./assets/MOJ_Lesser_Arms_Stacked_HEX_215x215.jpg"
      display_name                   = "STG-AI-Deployed-Cookiecutter"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_contacts           = ["Sam.Lhuillier@justice.gov.uk", "Harry.Waterman@justice.gov.uk", "Ehsan.Ashouri@justice.gov.uk", "Francis.webb1@justice.gov.uk"]
      owners                         = ["Sam.Lhuillier@justice.gov.uk", "Harry.Waterman@justice.gov.uk", "Ehsan.Ashouri@justice.gov.uk", "Francis.webb1@justice.gov.uk"]
      allowed_groups                 = ["Justice-ai-unit-staff"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = [
        "https://deployedcookiecutter-prod-frontend.azurewebsites.net/.auth/login/aad/callback",
        "https://deployedcookiecutter-preprod-frontend.azurewebsites.net/.auth/login/aad/callback",
        "https://deployedcookiecutter-devl-frontend.azurewebsites.net/.auth/login/aad/callback"
      ]
      mobile_desktop_redirect_uris   = []
      access_token_issuance_enabled  = false
      id_token_issuance_enabled      = true
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
        custom_single_sign_on         = null
      }
      identifier_uris                = null
      api = {
        known_client_applications      = []
        mapped_claims_enabled          = false
        requested_access_token_version = null
        oauth2_permission_scope        = []
      }
      tags                           = []
      custom_application_permissions = []
      spa_redirect_uris              = []
    },
    "STG-AI-Smartinbox-Devl" = {
      notes                          = "Justice AI Smartinbox Devl App"
      service_management_reference   = "IDAM-5036"
      logo_image                     = "./assets/MOJ_Lesser_Arms_Stacked_HEX_215x215.jpg"
      display_name                   = "STG-AI-Smartinbox-Devl"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_contacts           = ["Sam.Lhuillier@justice.gov.uk", "Harry.Waterman@justice.gov.uk", "Ehsan.Ashouri@justice.gov.uk"]
      owners                         = ["Sam.Lhuillier@justice.gov.uk", "Harry.Waterman@justice.gov.uk", "Ehsan.Ashouri@justice.gov.uk"]
      allowed_groups                 = ["Justice-ai-unit-staff"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = ["https://smartinbox-devl-frontend.azurewebsites.net/.auth/login/aad/callback", "https://courtlistings-devl-frontend.azurewebsites.net/.auth/login/aad/callback"]
      mobile_desktop_redirect_uris   = []
      access_token_issuance_enabled  = false
      id_token_issuance_enabled      = true
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
        custom_single_sign_on         = null
      }
      identifier_uris                = null
      api = {
        known_client_applications      = []
        mapped_claims_enabled          = false
        requested_access_token_version = null
        oauth2_permission_scope        = []
      }
      tags                           = []
      custom_application_permissions = []
      spa_redirect_uris              = []
    },
    "STG-AI-Courts-Transcribe-Devl" = {
      notes                          = "Justice AI Courts Transcribe Devl App"
      service_management_reference   = "IDAM-5036"
      logo_image                     = "./assets/MOJ_Lesser_Arms_Stacked_HEX_215x215.jpg"
      display_name                   = "STG-AI-Courts-Transcribe-Devl"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_contacts           = ["Sam.Lhuillier@justice.gov.uk", "Harry.Waterman@justice.gov.uk", "Ehsan.Ashouri@justice.gov.uk"]
      owners                         = ["Sam.Lhuillier@justice.gov.uk", "Harry.Waterman@justice.gov.uk", "Ehsan.Ashouri@justice.gov.uk"]
      allowed_groups                 = ["CourtsTranscribe", "Justice-ai-unit-staff"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = ["https://courtstranscribe-devl-frontend.azurewebsites.net/.auth/login/aad/callback"]
      mobile_desktop_redirect_uris   = []
      access_token_issuance_enabled  = false
      id_token_issuance_enabled      = true
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read", "offline_access"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
        custom_single_sign_on         = null
      }
      identifier_uris                = null
      api = {
        known_client_applications      = []
        mapped_claims_enabled          = false
        requested_access_token_version = null
        oauth2_permission_scope        = []
      }
      tags                           = []
      custom_application_permissions = []
      spa_redirect_uris              = []
    },
    "STG-AI-Prison-Transcribe-Devl" = {
      notes                          = "Justice AI Prison Transcribe Devl App"
      service_management_reference   = "IDAM-5630"
      logo_image                     = "./assets/MOJ_Lesser_Arms_Stacked_HEX_215x215.jpg"
      display_name                   = "STG-AI-Prison-Transcribe-Devl"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_contacts           = ["Sam.Lhuillier@justice.gov.uk", "Harry.Waterman@justice.gov.uk", "Ehsan.Ashouri@justice.gov.uk"]
      owners                         = ["Sam.Lhuillier@justice.gov.uk", "Harry.Waterman@justice.gov.uk", "Ehsan.Ashouri@justice.gov.uk"]
      allowed_groups                 = ["Justice-ai-unit-staff"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = ["https://prisontranscribe-devl-frontend.azurewebsites.net/.auth/login/aad/callback"]
      mobile_desktop_redirect_uris   = []
      access_token_issuance_enabled  = false
      id_token_issuance_enabled      = true
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read", "offline_access"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
        custom_single_sign_on         = null
      }
      identifier_uris                = null
      api = {
        known_client_applications      = []
        mapped_claims_enabled          = false
        requested_access_token_version = null
        oauth2_permission_scope        = []
      }
      tags                           = []
      custom_application_permissions = []
      spa_redirect_uris              = []
    },
    "STG-AI-Caselaw-Verification-Devl" = {
      notes                          = "Justice AI Caselaw Verification Devl App"
      service_management_reference   = "IDAM-5036"
      logo_image                     = "./assets/MOJ_Lesser_Arms_Stacked_HEX_215x215.jpg"
      display_name                   = "STG-AI-Caselaw-Verification-Devl"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_contacts           = ["Sam.Lhuillier@justice.gov.uk", "Harry.Waterman@justice.gov.uk", "Ehsan.Ashouri@justice.gov.uk"]
      owners                         = ["Sam.Lhuillier@justice.gov.uk", "Harry.Waterman@justice.gov.uk", "Ehsan.Ashouri@justice.gov.uk"]
      allowed_groups                 = ["Justice-ai-unit-staff"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = ["https://caselawverification-devl-frontend.azurewebsites.net/.auth/login/aad/callback"]
      mobile_desktop_redirect_uris   = []
      access_token_issuance_enabled  = false
      id_token_issuance_enabled      = true
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
        custom_single_sign_on         = null
      }
      identifier_uris                = null
      api = {
        known_client_applications      = []
        mapped_claims_enabled          = false
        requested_access_token_version = null
        oauth2_permission_scope        = []
      }
      tags                           = []
      custom_application_permissions = []
      spa_redirect_uris              = []
    },
  }
}
