variable "location" {
  description = "Azure region for resources to be deployed to."
  type        = string
  default     = "uksouth"
}

variable "applications" {
  description = "Map of application details"
  type = map(object({
    notes                        = string
    service_management_reference = string
    display_name                 = string
    department_name              = string
    team_name                    = string
    application_name             = string
    create_access_package        = bool
    access_package_reviewers     = list(string)
    owners                       = list(string)
    allowed_groups               = list(string)
    homepage_url                 = string
    logout_url                   = string
    redirect_uris                = list(string)
    app_roles = list(object({
      allowed_member_types  = list(string)
      description           = string
      display_name          = string
      id                    = string
      value                 = string
      access_package_hidden = bool
    }))
    graph_application_permissions = list(string)
    graph_delegated_permissions   = list(string)
    tenants_required              = list(string)
    federated_identity_credentials = list(object({
      repo_name      = string
      display_name   = string
      description    = string
      subject_suffix = string
    }))
    service_principle = object({
      login_url                     = string
      notification_email_addresses  = list(string)
      preferred_single_sign_on_mode = string
      app_role_assignment_required  = bool
      account_enabled               = bool
      application_template_name     = string
      hide                          = bool
    })
    identifier_uris = list(string)
  }))
  default = {
    "justice-ai-magic-mail" = {
      notes                          = "Justice AI Team Magic Mail"
      service_management_reference   = "IDAM-2889"
      display_name                   = "justice-ai-magic-mail"
      department_name                = "Justic-Digital"
      team_name                      = "AI"
      application_name               = "justice-ai-magic-mail"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = []
      allowed_groups                 = []
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = null
      app_roles                      = []
      graph_application_permissions  = ["Mail.ReadWrite"]
      graph_delegated_permissions    = []
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
      }
      identifier_uris = null
    },
    "STG-AI-Family-Law-Prod" = {
      notes                          = "Justice AI Family Law Prod App"
      service_management_reference   = "IDAM-5036"
      display_name                   = "STG-AI-Family-Law-Prod"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_name               = "STG-AI-Family-Law-Prod"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Dan.James@justice.gov.uk", "Richard.Leyshon@justice.gov.uk", "Sam.Lhuillier@justice.gov.uk"]
      allowed_groups                 = ["MoJO - Users - All"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = ["https://familylaw-prod-frontend.azurewebsites.net/.auth/login/aad/callback"]
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read"]
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
      }
      identifier_uris = null
    },
    "STG-AI-Family-Law-Pre-Prod" = {
      notes                          = "Justice AI Family Law Pre-Prod App"
      service_management_reference   = "IDAM-5036"
      display_name                   = "STG-AI-Family-Law-Pre-Prod"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_name               = "STG-AI-Family-Law-Pre-Prod"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Dan.James@justice.gov.uk", "Richard.Leyshon@justice.gov.uk", "Sam.Lhuillier@justice.gov.uk"]
      allowed_groups                 = ["MoJO - Users - All"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = []
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read"]
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
      }
      identifier_uris = null
    },
    "STG-AI-Family-Law-Dev" = {
      notes                          = "Justice AI Family Law Dev App"
      service_management_reference   = "IDAM-5036"
      display_name                   = "STG-AI-Family-Law-Dev"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_name               = "STG-AI-Family-Law-Dev"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Dan.James@justice.gov.uk", "Richard.Leyshon@justice.gov.uk", "Sam.Lhuillier@justice.gov.uk"]
      allowed_groups                 = ["MoJO - Users - All"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = ["https://familylaw-dev-frontend.azurewebsites.net/.auth/login/aad/callback"]
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read"]
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
      }
      identifier_uris = null
    },
    "STG-AI-HR-Toolkit-Prod" = {
      notes                          = "Justice AI HR Toolkit Prod App"
      service_management_reference   = "IDAM-5036"
      display_name                   = "STG-AI-HR-Toolkit-Prod"
      department_name                = "Justic-Digital"
      team_name                      = "AI"
      application_name               = "STG-AI-HR-Toolkit-Prod"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Dan.James@justice.gov.uk", "Richard.Leyshon@justice.gov.uk", "Sam.Lhuillier@justice.gov.uk"]
      allowed_groups                 = ["MoJO - Users - All"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = ["https://hrtoolkit-prod-frontend.azurewebsites.net/.auth/login/aad/callback"]
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read"]
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
      }
      identifier_uris = null
    },
    "STG-AI-HR-Toolkit-Preprod" = {
      notes                          = "Justice AI HR Toolkit Pre Prod App"
      service_management_reference   = "IDAM-5036"
      display_name                   = "STG-AI-HR-Toolkit-Preprod"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_name               = "STG-AI-HR-Toolkit-Preprod"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Dan.James@justice.gov.uk", "Richard.Leyshon@justice.gov.uk", "Sam.Lhuillier@justice.gov.uk"]
      allowed_groups                 = ["MoJO - Users - All"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = []
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read"]
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
      }
      identifier_uris = null
    },
    "STG-AI-HR-Toolkit-Dev" = {
      notes                          = "Justice AI HR Toolkit Dev App"
      service_management_reference   = "IDAM-5036"
      display_name                   = "STG-AI-HR-Toolkit-Dev"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_name               = "STG-AI-HR-Toolkit-Dev"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Dan.James@justice.gov.uk", "Richard.Leyshon@justice.gov.uk", "Sam.Lhuillier@justice.gov.uk"]
      allowed_groups                 = ["MoJO - Users - All"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = ["https://hrtoolkit-dev-frontend.azurewebsites.net/.auth/login/aad/callback"]
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read"]
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
      }
      identifier_uris = null
    },
    "STG-AI-Justice-Transcribe-Prod" = {
      notes                          = "Justice AI Transcribe Prod App"
      service_management_reference   = "IDAM-5036"
      display_name                   = "STG-AI-Justice-Transcribe-Prod"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_name               = "STG-AI-Justice-Transcribe-Prod"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Dan.James@justice.gov.uk", "Richard.Leyshon@justice.gov.uk", "Sam.Lhuillier@justice.gov.uk"]
      allowed_groups                 = ["MoJO - Users - All"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = ["https://justicetranscribe-prod-frontend.azurewebsites.net/.auth/login/aad/callback"]
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read", "offline_access"]
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
      }
      identifier_uris = null
    },
    "STG-AI-Justice-Transcribe-Pre-Prod" = {
      notes                          = "Justice AI Transcribe Pre Prod App"
      service_management_reference   = "IDAM-5036"
      display_name                   = "STG-AI-Justice-Transcribe-Pre-Prod"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_name               = "STG-AI-Justice-Transcribe-Pre-Prod"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Dan.James@justice.gov.uk", "Richard.Leyshon@justice.gov.uk", "Sam.Lhuillier@justice.gov.uk"]
      allowed_groups                 = ["MoJO - Users - All"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = ["https://justicetranscribe-preprod-frontend.azurewebsites.net/.auth/login/aad/callback"]
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read", "offline_access"]
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
      }
      identifier_uris = null
    },
    "STG-AI-Justice-Transcribe-Dev" = {
      notes                          = "Justice AI Transcribe Dev App"
      service_management_reference   = "IDAM-5036"
      display_name                   = "STG-AI-Justice-Transcribe-Dev"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_name               = "STG-AI-Justice-Transcribe-Dev"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Dan.James@justice.gov.uk", "Richard.Leyshon@justice.gov.uk", "Sam.Lhuillier@justice.gov.uk"]
      allowed_groups                 = ["MoJO - Users - All"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = ["https://justicetranscribe-dev-frontend.azurewebsites.net/.auth/login/aad/callback"]
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read", "offline_access"]
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
      }
      identifier_uris = null
    },
    "STG-AI-Langfuse-Prod" = {
      notes                          = "Justice AI Langfuse Prod App"
      service_management_reference   = "IDAM-5036"
      display_name                   = "STG-AI-Langfuse-Prod"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_name               = "STG-AI-Langfuse-Prod"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Dan.James@justice.gov.uk", "Richard.Leyshon@justice.gov.uk", "Sam.Lhuillier@justice.gov.uk"]
      allowed_groups                 = ["MoJO - Users - All"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = ["https://langfuse-ai.justice.gov.uk/api/auth/callback/azure-ad"]
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read"]
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
      }
      identifier_uris = null
    },
    "STG-AI-Langfuse-Pre-Prod" = {
      notes                          = "Justice AI Langfuse Pre Prod App"
      service_management_reference   = "IDAM-5036"
      display_name                   = "STG-AI-Langfuse-Pre-Prod"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_name               = "STG-AI-Langfuse-Pre-Prod"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Dan.James@justice.gov.uk", "Richard.Leyshon@justice.gov.uk", "Sam.Lhuillier@justice.gov.uk"]
      allowed_groups                 = ["MoJO - Users - All"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = []
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read"]
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
      }
      identifier_uris = null
    },
    "STG-AI-Langfuse-Dev" = {
      notes                          = "Justice AI Langfuse Dev App"
      service_management_reference   = "IDAM-5036"
      display_name                   = "STG-AI-Langfuse-Dev"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_name               = "STG-AI-Langfuse-Dev"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Dan.James@justice.gov.uk", "Richard.Leyshon@justice.gov.uk", "Sam.Lhuillier@justice.gov.uk"]
      allowed_groups                 = ["MoJO - Users - All"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = []
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read"]
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
      }
      identifier_uris = null
    },
    "STG-AI-Learning-App-Prod" = {
      notes                          = "Justice AI Learning Prod App"
      service_management_reference   = "IDAM-5036"
      display_name                   = "STG-AI-Learning-App-Prod"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_name               = "STG-AI-Learning-App-Prod"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Dan.James@justice.gov.uk", "Richard.Leyshon@justice.gov.uk", "Sam.Lhuillier@justice.gov.uk"]
      allowed_groups                 = ["MoJO - Users - All"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = ["https://learningapp-prod-frontend.azurewebsites.net/.auth/login/aad/callback"]
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read"]
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
      }
      identifier_uris = null
    },
    "STG-AI-Learning-App-Preprod" = {
      notes                          = "Justice AI Learning Pre Prod App"
      service_management_reference   = "IDAM-5036"
      display_name                   = "STG-AI-Learning-App-Pre-Prod"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_name               = "STG-AI-Learning-App-Pre-Prod"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Dan.James@justice.gov.uk", "Richard.Leyshon@justice.gov.uk", "Sam.Lhuillier@justice.gov.uk"]
      allowed_groups                 = ["MoJO - Users - All"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = []
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read"]
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
      }
      identifier_uris = null
    },
    "STG-AI-Learning-App-Dev" = {
      notes                          = "Justice AI Learning App Dev"
      service_management_reference   = "IDAM-5036"
      display_name                   = "STG-AI-Learning-App-Dev"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_name               = "STG-AI-Learning-App-Dev"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Dan.James@justice.gov.uk", "Richard.Leyshon@justice.gov.uk", "Sam.Lhuillier@justice.gov.uk"]
      allowed_groups                 = ["MoJO - Users - All"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = ["https://learningapp-dev-frontend.azurewebsites.net/.auth/login/aad/callback"]
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read"]
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
      }
      identifier_uris = null
    },
    "STG-AI-Prison-Phone-Calls-Prod" = {
      notes                          = "Justice AI Prison Phone Calls App Prod"
      service_management_reference   = "IDAM-5036"
      display_name                   = "STG-AI-Prison-Phone-Calls-Prod"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_name               = "STG-AI-Prison-Phone-Calls-Prod"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Dan.James@justice.gov.uk", "Richard.Leyshon@justice.gov.uk", "Sam.Lhuillier@justice.gov.uk"]
      allowed_groups                 = ["MoJO - Users - All"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = ["https://prisonphonecalls-prod-frontend.azurewebsites.net/.auth/login/aad/callback", "https://prison.transcription.service.justice.gov.uk/.auth/login/aad/callback"]
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read"]
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
      }
      identifier_uris = null
    },
    "STG-AI-Prison-Phone-Calls-Preprod" = {
      notes                          = "Justice AI Prison Phone Calls App Pre Prod"
      service_management_reference   = "IDAM-5036"
      display_name                   = "STG-AI-Prison-Phone-Calls-Pre-Prod"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_name               = "STG-AI-Prison-Phone-Calls-Pre-Prod"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Dan.James@justice.gov.uk", "Richard.Leyshon@justice.gov.uk", "Sam.Lhuillier@justice.gov.uk"]
      allowed_groups                 = ["MoJO - Users - All"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = []
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read"]
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
      }
      identifier_uris = null
    },
    "STG-AI-Prison-Phone-Calls-Dev" = {
      notes                          = "Justice AI Prison Phone Calls App Dev"
      service_management_reference   = "IDAM-5036"
      display_name                   = "STG-AI-Prison-Phone-Calls-Dev"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_name               = "STG-AI-Prison-Phone-Calls-Dev"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Dan.James@justice.gov.uk", "Richard.Leyshon@justice.gov.uk", "Sam.Lhuillier@justice.gov.uk"]
      allowed_groups                 = ["MoJO - Users - All"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = ["https://prisonphonecalls-dev-frontend.azurewebsites.net/.auth/login/aad/callback"]
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read"]
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
      }
      identifier_uris = null
    },
    "STG-AI-Prompt-Hub-Prod" = {
      notes                          = "Justice AI Prompt Hub App Prod"
      service_management_reference   = "IDAM-5036"
      display_name                   = "STG-AI-Prompt-Hub-Prod"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_name               = "STG-AI-Prompt-Hub-Prod"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Dan.James@justice.gov.uk", "Richard.Leyshon@justice.gov.uk", "Sam.Lhuillier@justice.gov.uk"]
      allowed_groups                 = ["MoJO - Users - All"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = ["https://prompthub-prod-frontend.azurewebsites.net/.auth/login/aad/callback", "https://ai-for-all.justice.gov.uk/.auth/login/aad/callback"]
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read"]
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
      }
      identifier_uris = null
    },
    "STG-AI-Prompt-Hub-Preprod" = {
      notes                          = "Justice AI Prompt Hub App Pre prod"
      service_management_reference   = "IDAM-5036"
      display_name                   = "STG-AI-Prompt-Hub-Preprod"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_name               = "STG-AI-Prompt-Hub-Preprod"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Dan.James@justice.gov.uk", "Richard.Leyshon@justice.gov.uk", "Sam.Lhuillier@justice.gov.uk"]
      allowed_groups                 = ["MoJO - Users - All"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = []
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read"]
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
      }
      identifier_uris = null
    },
    "STG-AI-Prompt-Hub-Dev" = {
      notes                          = "Justice AI Prompt Hub App Dev"
      service_management_reference   = "IDAM-5036"
      display_name                   = "STG-AI-Prompt-Hub-Dev"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_name               = "STG-AI-Prompt-Hub-Dev"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Dan.James@justice.gov.uk", "Richard.Leyshon@justice.gov.uk", "Sam.Lhuillier@justice.gov.uk"]
      allowed_groups                 = ["MoJO - Users - All"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = ["https://prompthub-dev-frontend.azurewebsites.net/.auth/login/aad/callback"]
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read"]
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
      }
      identifier_uris = null
    },
    "STG-AI-Redbox-Tracker-Prod" = {
      notes                          = "Justice AI Redbox Tracker App Prod"
      service_management_reference   = "IDAM-5036"
      display_name                   = "STG-AI-Redbox-Tracker-Prod"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_name               = "STG-AI-Redbox-Tracker-Prod"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Dan.James@justice.gov.uk", "Richard.Leyshon@justice.gov.uk", "Sam.Lhuillier@justice.gov.uk"]
      allowed_groups                 = ["MoJO - Users - All"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = ["https://redbox-tracker-prod-frontend.azurewebsites.net/.auth/login/aad/callback"]
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read"]
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
      }
      identifier_uris = null
    },
    "STG-AI-Redbox-Tracker-Preprod" = {
      notes                          = "Justice AI Redbox Tracker App Pre Prod"
      service_management_reference   = "IDAM-5036"
      display_name                   = "STG-AI-Redbox-Tracker-Preprod"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_name               = "STG-AI-Redbox-Tracker-Preprod"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Dan.James@justice.gov.uk", "Richard.Leyshon@justice.gov.uk", "Sam.Lhuillier@justice.gov.uk"]
      allowed_groups                 = ["MoJO - Users - All"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = []
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read"]
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
      }
      identifier_uris = null
    },
    "STG-AI-Redbox-Tracker-Dev" = {
      notes                          = "Justice AI Redbox Tracker App Dev"
      service_management_reference   = "IDAM-5036"
      display_name                   = "STG-AI-Redbox-Tracker-Dev"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_name               = "STG-AI-Redbox-Tracker-Dev"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Dan.James@justice.gov.uk", "Richard.Leyshon@justice.gov.uk", "Sam.Lhuillier@justice.gov.uk"]
      allowed_groups                 = ["MoJO - Users - All"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = ["https://redbox-tracker-dev-frontend.azurewebsites.net/.auth/login/aad/callback"]
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read"]
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
      }
      identifier_uris = null
    },
    "STG-AI-Risk-Register-Prod" = {
      notes                          = "Justice AI Risk Register Prod App"
      service_management_reference   = "IDAM-5036"
      display_name                   = "STG-AI-Risk-Register-Prod"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_name               = "STG-AI-Risk-Register-Prod"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Dan.James@justice.gov.uk", "Richard.Leyshon@justice.gov.uk", "Sam.Lhuillier@justice.gov.uk"]
      allowed_groups                 = ["MoJO - Users - All"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = ["https://riskregister-prod-frontend.azurewebsites.net/.auth/login/aad/callback"]
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read"]
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
      }
      identifier_uris = null
    },
    "STG-AI-Risk-Register-Preprod" = {
      notes                          = "Justice AI Risk Register Pre Prod App"
      service_management_reference   = "IDAM-5036"
      display_name                   = "STG-AI-Risk-Register-Preprod"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_name               = "STG-AI-Risk-Register-Preprod"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Dan.James@justice.gov.uk", "Richard.Leyshon@justice.gov.uk", "Sam.Lhuillier@justice.gov.uk"]
      allowed_groups                 = ["MoJO - Users - All"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = []
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read"]
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
      }
      identifier_uris = null
    },
    "STG-AI-Risk-Register-Dev" = {
      notes                          = "Justice AI Risk Register Dev App"
      service_management_reference   = "IDAM-5036"
      display_name                   = "STG-AI-Risk-Register-Dev"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_name               = "STG-AI-Risk-Register-Dev"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Dan.James@justice.gov.uk", "Richard.Leyshon@justice.gov.uk", "Sam.Lhuillier@justice.gov.uk"]
      allowed_groups                 = ["MoJO - Users - All"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = ["https://riskregister-dev-frontend.azurewebsites.net/.auth/login/aad/callback"]
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read"]
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
      }
      identifier_uris = null
    },
    "STG-AI-Smartinbox-Prod" = {
      notes                          = "Justice AI Smartinbox Prod App"
      service_management_reference   = "IDAM-5036"
      display_name                   = "STG-AI-Smartinbox-Prod"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_name               = "STG-AI-Smartinbox-Prod"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Dan.James@justice.gov.uk", "Richard.Leyshon@justice.gov.uk", "Sam.Lhuillier@justice.gov.uk", "Francis.Webb1@justice.gov.uk"]
      allowed_groups                 = ["MoJO - Users - All"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = ["https://smartinbox-prod-frontend.azurewebsites.net/.auth/login/aad/callback", "https://courtlistings-prod-frontend.azurewebsites.net/.auth/login/aad/callback"]
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read"]
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
      }
      identifier_uris = null
    },
    "STG-AI-Smartinbox-Preprod" = {
      notes                          = "Justice AI Smartinbox Preprod App"
      service_management_reference   = "IDAM-5036"
      display_name                   = "STG-AI-Smartinbox-Preprod"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_name               = "STG-AI-Smartinbox-Preprod"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Dan.James@justice.gov.uk", "Richard.Leyshon@justice.gov.uk", "Sam.Lhuillier@justice.gov.uk"]
      allowed_groups                 = ["MoJO - Users - All"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = ["https://smartinbox-preprod-frontend.azurewebsites.net/.auth/login/aad/callback"]
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read"]
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
      }
      identifier_uris = null
    },
    "STG-AI-Smartinbox-Dev" = {
      notes                          = "Justice AI Smartinbox Dev App"
      service_management_reference   = "IDAM-5036"
      display_name                   = "STG-AI-Smartinbox-Dev"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_name               = "STG-AI-Smartinbox-Dev"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Dan.James@justice.gov.uk", "Richard.Leyshon@justice.gov.uk", "Sam.Lhuillier@justice.gov.uk", "Francis.Webb1@justice.gov.uk"]
      allowed_groups                 = ["MoJO - Users - All"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = ["https://smartinbox-dev-frontend.azurewebsites.net/.auth/login/aad/callback", "https://courtlistings-dev-frontend.azurewebsites.net/.auth/login/aad/callback"]
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read"]
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
      }
      identifier_uris = null
    },
    "STG-AI-Translate-Prod" = {
      notes                          = "Justice AI Translate Prod App"
      service_management_reference   = "IDAM-5036"
      display_name                   = "STG-AI-Translate-Prod"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_name               = "STG-AI-Translate-Prod"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Dan.James@justice.gov.uk", "Richard.Leyshon@justice.gov.uk", "Sam.Lhuillier@justice.gov.uk"]
      allowed_groups                 = ["MoJO - Users - All"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = ["https://aitranslate-prod-frontend.azurewebsites.net/.auth/login/aad/callback"]
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read"]
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
      }
      identifier_uris = null
    },
    "STG-AI-Translate-Preprod" = {
      notes                          = "Justice AI Translate Pre Prod App"
      service_management_reference   = "IDAM-5036"
      display_name                   = "STG-AI-Translate-Preprod"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_name               = "STG-AI-Translate-Preprod"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Dan.James@justice.gov.uk", "Richard.Leyshon@justice.gov.uk", "Sam.Lhuillier@justice.gov.uk"]
      allowed_groups                 = ["MoJO - Users - All"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = ["https://smartinbox-preprod-frontend.azurewebsites.net/.auth/login/aad/callback"]
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read"]
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
      }
      identifier_uris = null
    },
    "STG-AI-Translate-Dev" = {
      notes                          = "Justice AI Translate Dev App"
      service_management_reference   = "IDAM-5036"
      display_name                   = "STG-AI-Translate-Dev"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_name               = "STG-AI-Translate-Dev"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Dan.James@justice.gov.uk", "Richard.Leyshon@justice.gov.uk", "Sam.Lhuillier@justice.gov.uk"]
      allowed_groups                 = ["MoJO - Users - All"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = ["https://aitranslate-dev-example.azurewebsites.net/.auth/login/aad/callback"]
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read"]
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
      }
      identifier_uris = null
    },
    "STG-AI-Courts-Transcribe-Prod" = {
      notes                          = "Justice AI Courts Transcribe Prod App"
      service_management_reference   = "IDAM-5036"
      display_name                   = "STG-AI-Courts-Transcribe-Prod"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_name               = "STG-AI-Courts-Transcribe-Prod"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Dan.James@justice.gov.uk", "Richard.Leyshon@justice.gov.uk", "Sam.Lhuillier@justice.gov.uk"]
      allowed_groups                 = ["MoJO - Users - All"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = ["https://courtstranscribe-prod-frontend.azurewebsites.net/.auth/login/aad/callback"]
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read", "offline_access"]
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
      }
      identifier_uris = null
    },
    "STG-AI-Courts-Transcribe-Preprod" = {
      notes                          = "Justice AI Courts Transcribe Pre Prod App"
      service_management_reference   = "IDAM-5036"
      display_name                   = "STG-AI-Courts-Transcribe-Preprod"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_name               = "STG-AI-Courts-Transcribe-Preprod"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Dan.James@justice.gov.uk", "Richard.Leyshon@justice.gov.uk", "Sam.Lhuillier@justice.gov.uk"]
      allowed_groups                 = ["MoJO - Users - All"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = ["https://courtstranscribe-preprod-frontend.azurewebsites.net/.auth/login/aad/callback"]
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read"]
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
      }
      identifier_uris = null
    },
    "STG-AI-Courts-Transcribe-Dev" = {
      notes                          = "Justice AI Courts Transcribe Dev App"
      service_management_reference   = "IDAM-5036"
      display_name                   = "STG-AI-Courts-Transcribe-Dev"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_name               = "STG-AI-Courts-Transcribe-Dev"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Dan.James@justice.gov.uk", "Richard.Leyshon@justice.gov.uk", "Sam.Lhuillier@justice.gov.uk"]
      allowed_groups                 = ["MoJO - Users - All"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = ["https://courtstranscribe-dev-frontend.azurewebsites.net/.auth/login/aad/callback"]
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read", "offline_access"]
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
      }
      identifier_uris = null
    },
    "STG-AI-Prison-Transcribe-Dev" = {
      notes                          = "Justice AI Prison Transcribe Dev App"
      service_management_reference   = "IDAM-5630"
      display_name                   = "STG-AI-Prison-Transcribe-Dev"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_name               = "STG-AI-Prison-Transcribe-Dev"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Dan.James@justice.gov.uk", "Richard.Leyshon@justice.gov.uk", "Sam.Lhuillier@justice.gov.uk", "Ehsan.Ashouri@justice.gov.uk"]
      allowed_groups                 = ["MoJO - Users - All"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = ["https://prisontranscribe-dev-frontend.azurewebsites.net/.auth/login/aad/callback"]
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read", "offline_access"]
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
      }
      identifier_uris = null
    },
    "STG-AI-Prison-Transcribe-Preprod" = {
      notes                          = "Justice AI Prison Transcribe PreProd App"
      service_management_reference   = "IDAM-5630"
      display_name                   = "STG-AI-Prison-Transcribe-Preprod"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_name               = "STG-AI-Prison-Transcribe-Preprod"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Dan.James@justice.gov.uk", "Richard.Leyshon@justice.gov.uk", "Sam.Lhuillier@justice.gov.uk"]
      allowed_groups                 = ["MoJO - Users - All"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = ["https://prisontranscribe-preprod-frontend.azurewebsites.net/.auth/login/aad/callback"]
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read"]
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
      }
      identifier_uris = null
    },
    "STG-AI-Prison-Transcribe-Prod" = {
      notes                          = "Justice AI Prison Transcribe Prod App"
      service_management_reference   = "IDAM-5630"
      display_name                   = "STG-AI-Prison-Transcribe-Prod"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_name               = "STG-AI-Prison-Transcribe-Prod"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Dan.James@justice.gov.uk", "Richard.Leyshon@justice.gov.uk", "Sam.Lhuillier@justice.gov.uk", "Ehsan.Ashouri@justice.gov.uk"]
      allowed_groups                 = ["MoJO - Users - All"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = ["https://prison.transcription.service.justice.gov.uk/.auth/login/aad/callback", "https://prisontranscribe-prod-frontend.azurewebsites.net/.auth/login/aad/callback"]
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read"]
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
      }
      identifier_uris = null
    },
    "STG-AI-Caselaw-Verification-Dev" = {
      notes                          = "Justice AI Caselaw Verification Dev App"
      service_management_reference   = "IDAM-5036"
      display_name                   = "STG-AI-Caselaw-Verification-Dev"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_name               = "STG-AI-Caselaw-Verification-Dev"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Dan.James@justice.gov.uk", "John.Daley@justice.gov.uk", "Sam.Lhuillier@justice.gov.uk"]
      allowed_groups                 = ["MoJO - Users - All"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = ["https://caselawverification-dev-frontend.azurewebsites.net/.auth/login/aad/callback"]
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read"]
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
      }
      identifier_uris = null
    },
    "STG-AI-Caselaw-Verification-Preprod" = {
      notes                          = "Justice AI Caselaw Verification Pre Prod App"
      service_management_reference   = "IDAM-5036"
      display_name                   = "STG-AI-Caselaw-Verification-Preprod"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_name               = "STG-AI-Caselaw-Verification-Preprod"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Dan.James@justice.gov.uk", "John.Daley@justice.gov.uk", "Sam.Lhuillier@justice.gov.uk"]
      allowed_groups                 = ["MoJO - Users - All"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = ["https://caselawverification-preprod-frontend.azurewebsites.net/.auth/login/aad/callback"]
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read"]
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
      }
      identifier_uris = null
    },
    "STG-AI-Caselaw-Verification-Prod" = {
      notes                          = "Justice AI Caselaw Verification Prod App"
      service_management_reference   = "IDAM-5036"
      display_name                   = "STG-AI-Caselaw-Verification-Prod"
      department_name                = "Justice-Digital"
      team_name                      = "AI"
      application_name               = "STG-AI-Caselaw-Verification-Prod"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Dan.James@justice.gov.uk", "John.Daley@justice.gov.uk", "Sam.Lhuillier@justice.gov.uk"]
      allowed_groups                 = ["MoJO - Users - All"]
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = ["https://caselawverification-prod-frontend.azurewebsites.net/.auth/login/aad/callback"]
      app_roles                      = []
      graph_application_permissions  = []
      graph_delegated_permissions    = ["email", "openid", "profile", "User.Read"]
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = null
      }
      identifier_uris = null
    }
  }
}
