repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
      exclude: '^\.idea/'
    - id: check-yaml
    - id: no-commit-to-branch
- repo: https://github.com/awslabs/git-secrets
  rev: master
  hooks:
    - id: git-secrets

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.97.0
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
