variable "location" {
  description = "Azure region for resources to be deployed to."
  type        = string
  default     = "uksouth"
}

variable "applications" {
  description = "Map of application details"
  type = map(object({
    notes                        = string
    service_management_reference = string
    display_name                 = string
    department_name              = string
    team_name                    = string
    application_name             = string
    create_access_package        = bool
    access_package_reviewers     = list(string)
    owners                       = list(string)
    allowed_groups               = list(string)
    homepage_url                 = string
    logout_url                   = string
    redirect_uris                = list(string)
    mobile_desktop_redirect_uris = list(string)
    app_roles = list(object({
      allowed_member_types  = list(string)
      description           = string
      display_name          = string
      id                    = string
      value                 = string
      access_package_hidden = bool
    }))
    graph_application_permissions = list(string)
    graph_delegated_permissions   = list(string)
    tenants_required              = list(string)
    federated_identity_credentials = list(object({
      repo_name      = string
      display_name   = string
      description    = string
      subject_suffix = string
    }))
    service_principle = object({
      login_url                     = string
      notification_email_addresses  = list(string)
      preferred_single_sign_on_mode = string
      app_role_assignment_required  = bool
      account_enabled               = bool
      application_template_name     = string
      hide                          = bool
    })
    identifier_uris = list(string)
  }))
  default = {
    "graph_permissions" = {
      notes                          = "This app is used to give delegated Graph API access"
      service_management_reference   = "IDAM-3659"
      display_name                   = "EUCS-MWP-Graph-API-Access"
      department_name                = "eucs"
      team_name                      = "mwp"
      application_name               = "EUCS-MWP-Graph-API-Access"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Shaun.Horton1@JusticeUK.onmicrosoft.com"]      
      allowed_groups                 = []
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = null
      mobile_desktop_redirect_uris   = null
      app_roles                      = []
      graph_application_permissions  = ["Group.Create"]
      graph_delegated_permissions    = ["DeviceManagementManagedDevices.Read.All", "AuditLog.Read.All", "Reports.Read.All", "Files.Read.All", "GroupMember.ReadWrite.All", "Group.ReadWrite.All", "TeamSettings.ReadWrite.All", "Team.ReadBasic.All", "Contacts.ReadWrite", "MailboxSettings.ReadWrite", "User.Read.All", "Mail.ReadBasic", "PartnerBilling.Read.All", "Organization.Read.All"]
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = true
      }
      identifier_uris = null
    },
    "MWPExchangeSP" = {
      notes                          = "This app is used to give application access to Exchange Online."
      service_management_reference   = "IDAM-3659"
      display_name                   = "EUCS-MWP-EXO-SPN-RW-MSGraphAPI-1.0"
      department_name                = "eucs"
      team_name                      = "mwp"
      application_name               = "ExchangeOnline"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Shaun.Horton1@JusticeUK.onmicrosoft.com"]      
      allowed_groups                 = []
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = null
      mobile_desktop_redirect_uris   = null
      app_roles                      = []
      graph_application_permissions  = ["Mail.Read.All", "MailboxSettings.ReadWrite", "Calendars.ReadWrite", "Contacts.ReadWrite"]
      graph_delegated_permissions    = []
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = true
      }
      identifier_uris = null
    },
      "MWPTeamsSP" = {
      notes                          = "This app is used to give application access to MS Teams."
      service_management_reference   = "IDAM-3659"
      display_name                   = "EUCS-MWP-MST-SPN-RW-MSGraphAPI-1.0"
      department_name                = "eucs"
      team_name                      = "mwp"
      application_name               = "MSTeams"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Shaun.Horton1@JusticeUK.onmicrosoft.com"]      
      allowed_groups                 = []
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = null
      mobile_desktop_redirect_uris   = null
      app_roles                      = []
      graph_application_permissions  = ["Directory.Read.All", "Group.ReadWrite.All", "GroupMember.ReadWrite.All", "Group.Create", "Group.Delete", "User.Read.All"]
      graph_delegated_permissions    = []
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = true
      }
      identifier_uris = null
    },
    "MWPUsersGroupSP" = {
      notes                          = "This app is used to give application access to Users and Groups."
      service_management_reference   = "IDAM-3659"
      display_name                   = "EUCS-MWP-UG-SPN-RW-MSGraphAPI-1.0"
      department_name                = "eucs"
      team_name                      = "mwp"
      application_name               = "UserGroups"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Shaun.Horton1@JusticeUK.onmicrosoft.com"]      
      allowed_groups                 = []
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = null
      mobile_desktop_redirect_uris   = null
      app_roles                      = []
      graph_application_permissions  = ["Directory.Read.All", "Group.ReadWrite.All", "GroupMember.ReadWrite.All", "Group.Create", "Group.Delete", "User.Read.All"]
      graph_delegated_permissions    = []
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = true
      }
      identifier_uris = null
    },
    "MWPSharePointSP" = {
      notes                          = "This app is used to give application access to SharePoint."
      service_management_reference   = "IDAM-3659"
      display_name                   = "EUCS-MWP-SPT-SPN-R-MSGraphAPI-1.0"
      department_name                = "eucs"
      team_name                      = "mwp"
      application_name               = "SharePoint"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Shaun.Horton1@JusticeUK.onmicrosoft.com"]      
      allowed_groups                 = []
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = null
      mobile_desktop_redirect_uris   = null
      app_roles                      = []
      graph_application_permissions  = ["Files.Read.All"]
      graph_delegated_permissions    = []
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = true
      }
      identifier_uris = null
    },
    "MWPLicenseBillingSP" = {
      notes                          = "This app is used to give application access to Licensing and Billing."
      service_management_reference   = "IDAM-3659"
      display_name                   = "EUCS-MWP-LAB-SPN-R-MSGraphAPI-1.0"
      department_name                = "eucs"
      team_name                      = "mwp"
      application_name               = "LicenseAndBilling"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Shaun.Horton1@JusticeUK.onmicrosoft.com"]      
      allowed_groups                 = []
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = null
      mobile_desktop_redirect_uris   = null
      app_roles                      = []
      graph_application_permissions  = ["Organization.Read.All", "Billing.Read.All"]
      graph_delegated_permissions    = []
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = true
      }
      identifier_uris = null
    },
    "MWPAuditInsightsSP" = {
      notes                          = "This app is used to give application access to Audit Insights."
      service_management_reference   = "IDAM-3659"
      display_name                   = "EUCS-MWP-AI-SPN-R-MSGraphAPI-1.0"
      department_name                = "eucs"
      team_name                      = "mwp"
      application_name               = "AuditInsights"
      create_access_package          = false
      access_package_reviewers       = []
      owners                         = ["Shaun.Horton1@JusticeUK.onmicrosoft.com"]      
      allowed_groups                 = []
      homepage_url                   = null
      logout_url                     = null
      redirect_uris                  = null
      mobile_desktop_redirect_uris   = null
      app_roles                      = []
      graph_application_permissions  = ["Reports.Read.All", "Usage.Read.All", "ActivityFeed.Read", "AuditLog.Read.All", "DeviceManagementManagedDevices.Read.All"]
      graph_delegated_permissions    = []
      tenants_required               = ["LIVE"]
      federated_identity_credentials = []
      service_principle = {
        login_url                     = null
        notification_email_addresses  = []
        preferred_single_sign_on_mode = null
        app_role_assignment_required  = true
        account_enabled               = true
        application_template_name     = null
        hide                          = true
      }
      identifier_uris = null
    }
  }
}
