name: "Rotate Secret"
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
      
jobs: 
  login-and-rotate:
    runs-on: ubuntu-latest
    steps:        
    - uses: actions/checkout@v4
    - name: 'Az CLI login with Federation credential'
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}          
        allow-no-subscriptions: true        
    - name: 'Rotate Application secret'
      uses: ./.github/actions/rotate-application-registration-secret/action.yaml
      id: rotate-secret
      with:
        secret-validity-in-days: 30
