name: "[Job] Azure Terraform Plan"

on:
  workflow_call:
    inputs:
      environment:
        description: 'The terraform environment to target'
        required: true
        type: string
      environment_path:
        description: 'The terraform environment path'
        required: true
        type: string
    secrets:
      arm_client_id:
        description: 'Azure ARM Client ID'
        required: true
      arm_tenant_id:
        description: 'ARM Tenant ID'
        required: true
      arm_subscription_id:
        description: 'ARM Subscription ID'
        required: true
      workspace_client_id:
        description: 'Azure ARM Client ID for TF Workspace'
        required: true
      workspace_tenant_id:
        description: 'ARM Tenant ID for TF Workspace'
        required: true
      github_access_token:
        description: 'Github Token'
        required: true

permissions:
  pull-requests: write
  issues: write
  id-token: write
  contents: read

jobs:
  terraform_plan_workflow:
    environment: ${{ inputs.environment}}
    name: "${{ inputs.environment}} plan"
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.arm_client_id }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.arm_subscription_id }}
      ARM_TENANT_ID: ${{ secrets.arm_tenant_id }}
      ARM_USE_OIDC: true
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init -input=false
        env:
          TF_VAR_tenant_id: ${{ secrets.workspace_tenant_id }}
          TF_VAR_client_id: ${{ secrets.workspace_client_id }}
          ARM_USE_OIDC: true
        working-directory: ${{ inputs.environment_path }}

      - name: Terraform Plan
        id: terraform_plan
        env:
          TF_VAR_tenant_id: ${{ secrets.workspace_tenant_id }}
          TF_VAR_client_id: ${{ secrets.workspace_client_id }}
          ARM_USE_OIDC: true
        working-directory: ${{ inputs.environment_path }}
        run: |
          terraform plan -lock-timeout=300s -input=false
