name: Trivy Static analysis

on:
  pull_request:
    branches: [ main ]
    paths:
      - "**.tf"

permissions:
  security-events: write
  contents: write
  actions: read

defaults:
  run:
    shell: bash

jobs:
  trivy-terraform-scan:
    name: Run Trivy Static Code Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Trivy v0.65.0
        uses: aquasecurity/setup-trivy@v0.2.3
        with:
          trivy-version: v0.65.0
        cache: true 

      - name: Run Trivy Config Scan
        run: |
          trivy config . \
            --severity HIGH,CRITICAL \
            --format sarif \
            --output trivy-results.sarif \
            --ignore-unfixed \
            --exit-code 1 \
            --skip-version-check

      - name: Upload SARIF Report to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results.sarif"
