name: "[Validation] Validate Code"
on:
  workflow_call:
    inputs:
      environment_path:
        description: 'Azure Environment'
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - uses: terraform-linters/setup-tflint@v4
        name: Setup TFLint

      - name: Format Terraform
        working-directory: ${{ inputs.environment_path }}
        run: terrafrorm fmt -check -recursive

      
      - name: Terraform Lint 
        working-directory: ${{ inputs.environment_path }}
        run: tflint --recursive
  

      - name: Terraform Validate 
        working-directory: ${{ inputs.environment_path }}
        run: |
          terraform --version
          terraform init
          terraform validate
