name: "[Validation] Validate Code"
on:
  workflow_call:
    inputs:
      environment_path:
        description: 'Environment Path'
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - uses: terraform-linters/setup-tflint@v4
        name: Setup TFLint
        continue-on-error: true

      - name: terraform init
        run: terraform init -input=false
        env:
          TF_VAR_tenant_id: ${{ secrets.workspace_tenant_id }}
          TF_VAR_client_id: ${{ secrets.workspace_client_id }}
          ARM_USE_OIDC: true
        working-directory: ${{ inputs.environment_path }}

      - name: format terraform
        working-directory: ${{ inputs.environment_path }}
        run: terraform fmt -check -recursive

      - name: terraform lint 
        working-directory: ${{ inputs.environment_path }}
        run: tflint --recursive
  
      - name: terraform validate 
        working-directory: ${{ inputs.environment_path }}
        run: |
          terraform --version
          terraform init
          terraform validate
