name: "[Workflow] PR"

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select the environment
        required: true
        options:
          - DEVL
          - NLE
          - LIVE

defaults:
  run:
    shell: bash

permissions:
  id-token: write
  contents: write
  security-events: write
  pull-requests: write
  actions: none
  checks: none
  deployments: none
  issues: write
  packages: none
  repository-projects: none
  statuses: none

jobs:
  
  validate_code:
    name: validate code
    uses: ./.github/workflows/validate_code.yml
    with:
      environment: ${{ inputs.environment }}

  # terraform_plan_workflow:
  #   name: tf plan ${{ matrix.environment }}
  #   uses: ./.github/workflows/terraform_plan_job.yml
  #   needs: 
  #     - validate_code
  #   strategy:
  #     matrix:
  #       environment: [devl, nle, live]
  #   with:
  #     environment: ${{ matrix.environment}}
  #     environment_path: 'terraform/envs/${{ matrix.environment }}'
  #   secrets:
  #     arm_subscription_id: ${{ secrets.arm_subscription_id }}
  #     arm_tenant_id: ${{ secrets.arm_tenant_id }}
  #     arm_client_id: ${{ secrets.arm_client_id }}
  #     workspace_tenant_id: ${{ secrets.workspace_tenant_id }}
  #     workspace_client_id: ${{ secrets.workspace_client_id }}
  #     github_access_token: ${{ secrets.GITHUB_TOKEN }}
