name: "[Workflow] Path To Live"

on:
  push:
    branches:
      - main
    paths:
      - terraform/**
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  security-events: write
  pull-requests: write
  issues: write

defaults:
  run:
    shell: bash

env:
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}

jobs:
  terraform:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [DEVL, NLE, LIVE]

    environment: ${{ matrix.environment }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login via OIDC
        uses: azure/login@v2
        with:
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          client-id: ${{ secrets.ARM_CLIENT_ID }}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build Go Terraform Runner
        run: go build -o terraform-runner ./scripts/pipeline/main.go

      - name: Terraform Init
        run: ./terraform-runner -env "${{ matrix.environment }}" -cmd "init -backend-config=./state.config"

      - name: Terraform Validate
        run: ./terraform-runner -env "${{ matrix.environment }}" -cmd "validate"

      - name: Terraform Format
        run: ./terraform-runner -env "${{ matrix.environment }}" -cmd "fmt"

      - name: Terraform Plan and Apply
        run: ./terraform-runner -env "${{ matrix.environment }}" -cmd "apply" -applyMode
