name: "[Workflow] Pull Request"

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  security-events: write
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:
    terraform:
      runs-on: ubuntu-latest

      environment: DEVL

      env:
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}

      steps:

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          allow-no-subscriptions: true  

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Terraform Init
        working-directory: ./terraform/envs/devl
        run: terraform init -input=false

      - name: Terraform Validate
        working-directory: ./terraform/envs/devl
        run: terraform validate

      - name: Terraform Format
        working-directory: ./terraform/envs/devl
        run: terraform fmt

      - name: Terraform Plan
        working-directory: ./terraform/envs/devl
        run: terraform plan -lock-timeout=300s -input=false

