name: "[Workflow] Pull Request"

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  security-events: write
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:
    terraform:
      runs-on: ubuntu-latest

      environment: DEVL

      steps:

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          allow-no-subscriptions: true  

      - name: Checkout Code
        uses: actions/checkout@v4

      # - name: Azure CLI script
      #   uses: azure/cli@v2.1.0
      #   with:
      #     azcliversion: latest
      #     inlineScript: |
      #       az account show

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/envs/devl
        env:
          TF_VAR_client_id: ${{ secrets.ARM_CLIENT_ID }}
          TF_VAR_tenant_id: ${{ secrets.AMR_TENANT_ID }}
