name: "[Workflow] Pull Request"

on:
  pull_request:

permissions:
  id-token: write
  security-events: write
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:
    
    run_terraform:
      name: Run Terraform


