name: "[Workflow] Pull Request"

on:
  pull_request:

permissions:
  contents: read
  id-token: write
  security-events: write
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:

  terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [DEVL, NLE, LIVE]
        customers: [idam-internal]

    environment: ${{ matrix.environment }}

    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Azure Login via OIDC
      uses: azure/login@v2
      with:
        subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        tenant-id: ${{ secrets.ARM_TENANT_ID }}
        client-id: ${{ secrets.ARM_CLIENT_ID }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      working-directory: ./terraform/envs/${{matrix.environment}}/${{ matrix.customers }}
      run: terraform init -backend-config="./state.config"

    - name: Terraform Validate
      working-directory: ./terraform/envs/${{matrix.environment}}/${{ matrix.customers }}
      run: terraform validate

    - name: Terraform Format
      working-directory: ./terraform/envs/${{matrix.environment}}/${{ matrix.customers }}
      run: terraform fmt

    - name: Terraform Plan
      working-directory: ./terraform/envs/${{matrix.environment}}/${{ matrix.customers }}
      run: terraform plan -lock-timeout=300s -input=false
